version: "3.4"

services:
  postgres:
    image: postgres:latest
    ports:
      - "5432:5432"
    volumes:
      - crmd_postgres:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: postgres
      POSTGRES_DB: crimewatch_dev
      POSTGRES_PASSWORD: crimewatch_dev

    restart: always 
    networks:
      - mynetwork

volumes:
  crmd_postgres:

networks:
  mynetwork:
