services:
  postgres:
    image: postgres:latest
    ports:
      - "5432:5432"
    volumes:
      - crmd_postgres_dev:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: postgres
      POSTGRES_DB: crimewatch_dev
      POSTGRES_PASSWORD: crimewatch_dev

    restart: always 
    networks:
      - mynetwork
  redis:
    image: redis:latest
    restart: always
    volumes:
      - redis_volume_data_dev:/data
    ports:
      - 6379:6379
    networks:
      - mynetwork
  redis_insight:
    image: redislabs/redisinsight:1.14.0
    container_name: redis_insight
    restart: always
    ports:
      - 8001:8001
    volumes:
      - redis_insight_volume_data_dev:/db

volumes:
  crmd_postgres_dev:
  redis_volume_data_dev:
  redis_insight_volume_data_dev:

networks:
  mynetwork:
