services:
  postgres:
    image: postgres:latest
    ports:
      - "5432:5432"
    volumes:
      - crmd_postgres_dev:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: postgres
      POSTGRES_DB: crimewatch_dev
      POSTGRES_PASSWORD: crimewatch_dev

    restart: always 
    networks:
      - mynetwork
  redis:
    image: redis:latest
    restart: always
    volumes:
      - redis_volume_data_dev:/data
    ports:
      - 6379:6379
    networks:
      - mynetwork

volumes:
  crmd_postgres_dev:
  redis_volume_data_dev:

networks:
  mynetwork:
